title: OpenCore Configuration
description: A GitHub Pages hosted website that mirrors OpenCorePkg Configuration.pdf
theme: just-the-docs

url: https://dreamwhite.github.io/OpenCorePkg-Docs

aux_links:
  Original Configuration.pdf: https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf
