title: OpenCore Configuration
description: A GitHub Pages hosted website that mirrors OpenCorePkg Configuration.pdf
theme: just-the-docs

url: https://dreamwhite.github.io/OpenCorePkg-Docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
